# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.3
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: yared@679labs.com
author_name: Yared EA
cloud_provider: none
contract_name: mahber
deployment_language: python
ide_vscode: true
preset_name: production
project_name: mahber
python_linter: ruff
use_dispenser: false
use_github_actions: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

